imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        # replace 'main' by the name of your own firewall
        main:
            http_basic: ~